name: 🚀 Deploy to GCP VM

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy on GCP VM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: Pull and Deploy Code
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
            cd ${{ secrets.APP_DIR }}

            # Pull latest changes
            git pull origin main

            # Install dependencies
            npm install

            # Restart app with PM2
            pm2 restart all || pm2 start app.js --name my-app

            # Reload nginx if needed
            sudo systemctl reload nginx
          EOF
